### ISSUE TITLE
Cound you port this to Rider?

### ISSUE THREAD

**Issue by Giresharu** [AskMeAgain/EndOfLineHint#1]
Thank you!

**Comment by AskMeAgain** [comment]
Hey sorry, but that would take me to much time right now. Its not so straight forward as i have to install Rider and try to lookup how it works there.

But feel free to copy the code. Overall its not so much and you can get an explanation on how to release a plugin to the intellij store here: https://github.com/AskMeAgain/IntellijPluginTemplate

**Comment by Giresharu** [comment]
Thanks for your reply! I'll try it.
